### ISSUE TITLE
feat: getting the name(s) of generated test file(s) in command's output

### ISSUE THREAD

**Issue by GuillaumeSMedia** [paul-thebaud/phpunitgen-console#11]
### Subject of the issue
I created a Visual Studio Code task to generate a test file for the current file.

The task works, but I cannot find a way to get the name of the generated file in PHPUnitGen's output. Am I missing something?

### Your environment
* version of `phpunitgen/core`:
* version of `phpunitgen/console`: PhpUnitGen 4.2.0

### Steps to reproduce
Run the the command as follows:

![Screenshot 2023-01-29 at 18 40 56](https://user-images.githubusercontent.com/2572154/215345555-5dab279b-4c72-4e88-98e3-429cb0d36d9c.png)

### Expected behaviour
Verbose options should offer more verbosity as to which files are created.

### Actual behaviour
No options seem to offer displaying the name of created test file(s). Or am I missing something?

Thanks in advance! Great tool!

**Comment by paul-thebaud** [comment]
Hello @GuillaumeSMedia and thank you for this issue.
If I understand correctly, what you expect is the verbose option to print the generated file name instead of only a progress bar?
This is currently not possible, as the [PhpUnitGen process handler](https://github.com/paul-thebaud/phpunitgen-console/blob/main/src/Execution/ProcessHandler.php#L122) will only print more information about warnings/errors when using the verbose option.
I'll take a look into this soon.

**Comment by GuillaumeSMedia** [comment]
Thank you for the quick reply. You understood correctly.

Wether it's done via the verbose option or a dedicated option, being able to print the generated file name instead of a progress bar would open new possibilities, such as parsing the generated file name and instructing the IDE to open the newly generated file automatically.

**Comment by paul-thebaud** [comment]
Ok. So maybe the better way to do this is to provide a `--report` option where you give a reporter to use. By default, the text reporter will be used (the current one), but we can imagine a JSON reporter which will print a JSON report object.
Can a new feature like this solve your issue?

**Comment by GuillaumeSMedia** [comment]
That would be fantastic! When the feature is implemented I can port my VSCode Task to a public extension, so that other people can benefit from it too.

**Comment by paul-thebaud** [comment]
Great! I'll keep in touch. I want the reporters feature to be as flexible as possible and correctly implemented.

**Comment by paul-thebaud** [comment]
Hello @GuillaumeSMedia, I pushed some changes which will be released as V5. It adds a `--json` command option, which will print a JSON report instead of the textual default one.

You can install it using `composer require phpunitgen/console:dev-main`.

Here is an example of the output JSON report:

```json
{
    "summary": {
        "sources": 1,
        "successes": 1,
        "warnings": 0,
        "errors": 0,
        "time": 38,
        "memory": 14680064
    },
    "results": {
        "app\/Models\/User.php": {
            "status": "success",
            "path": "tests\/Unit\/Models\/UserTest.php",
            "message": "Successful generation"
        }
    }
}
```

Please let me know if there is anything you would like to see improved/changed :)

**Comment by GuillaumeSMedia** [comment]
Hi @paul-thebaud, I've just tested the `--json` option and it works like a charm!

With the following VSCode Task configuration, I am able to run PhpUnitGen on the current file and automatically open the generated test file:

```
        "tasks": [
            {
                "label": "Create PHPUnit Test",
                "type": "shell",
                "command": "output=$(docker-compose run --no-TTY php ./vendor/bin/phpunitgen --json ${relativeFile} tests/unit) && path=$(echo \"$output\" | jq -r '.results[].path') && [[ ! -z \"$path\" ]] && \"${execPath}\" \"$path\" || (echo \"error: no path found in JSON output\" && exit 1)",
                "problemMatcher": []
            },
        ]
```

I can't think of any additional changes. Thank you so much for your responsiveness! 🙏 

I'll have a closer look at creating a proper VSCode extension in the next few days, so that other people can add this feature to their IDE with a few clicks.

**Comment by paul-thebaud** [comment]
Hello @GuillaumeSMedia,
Thanks! Great work! :tada: 
I don't know if there is an impact, but keep in mind that the path of the source file and created test file might be an absolute path.

**Comment by paul-thebaud** [comment]
I'll let you a few days before releasing a stable V5 with this new feature. Feel free to ask if you need anything else uppon release.

**Comment by paul-thebaud** [comment]
@GuillaumeSMedia: a last thing about the report. If you plan to distribute your VSCode extension, you should correctly handle warnings and errors as those won't result in a test file creation.

**Comment by paul-thebaud** [comment]
Hello @GuillaumeSMedia,
I would like to release a stable V5 soon. Do you have any feedback on it? How about your VSCode extension publication?

**Comment by paul-thebaud** [comment]
Great, thank you for the feedback, and no problem!
I'll release this soon, and I'll close the issue when it's done!

**Comment by paul-thebaud** [comment]
Closing as V5 is now released with the feature.
Feel free to comment on this thread or open a new issue if needed.
