### ISSUE TITLE
PHP 8.3 requirement

### ISSUE THREAD

**Issue by grotadmorv** [paul-thebaud/phpunitgen-console#13]
### Subject of the issue
unable to update phpunitgen tools while using php 8.3 version

### Your environment
* version of `phpunitgen/core`: /
* version of `phpunitgen/console`: 5.0.0

### Steps to reproduce
`composer require --dev phpunitgen/console`
<img width="1075" alt="Capture d’écran 2023-12-18 à 15 44 59" src="https://github.com/paul-thebaud/phpunitgen-console/assets/25185509/0bd1bd1a-40cd-4817-8054-22064224a9ab">

If you can add php 8.3 version, it will be nice, thanks you !

**Comment by paul-thebaud** [comment]
I'll try to add PHP 8.3. maybe some deps will cause problems, so I'll keep in touch here! Thanks for the report.

**Comment by paul-thebaud** [comment]
Hi @grotadmorv, PHP8.3 support is available on v6.1.0. Thanks for your report!
